[package]
name = "desub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

desub-legacy = { path = "../desub-legacy/", package = "desub-legacy" }
desub-common = { path = "../desub-common/", package = "desub-common" }
desub-current = { path = "../desub-current/", package = "desub-current" }
json-resolver = { path = "../desub-json-resolver/", optional = true, package = "desub-json-resolver" }

thiserror = "1.0.30"
frame-metadata = "14.2"
codec = { version = "2.3.1", package = "parity-scale-codec" }
serde_json = "1.0.68"

[features]
polkadot-js = ["json-resolver", "json-resolver/polkadot-js", "frame-metadata/legacy" ]
