[package]
name = "desub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

desub-legacy = { path = "../desub-legacy/" }
desub-common = { path = "../desub-common/" }
desub-current = { path = "../desub-current/" }
desub-json-resolver = { path = "../desub-json-resolver/", optional = true }

thiserror = "1.0.30"
frame-metadata = { git = "https://github.com/paritytech/frame-metadata", branch = "insipx-aj-docs-rebase" }
codec = { version = "2.3.1", package = "parity-scale-codec" }
serde = { version = "1", features = ["derive"] }


[features]
polkadot-js = ["desub-json-resolver", "desub-json-resolver/polkadot", "frame-metadata/legacy" ]
