[package]
name = "v14-test"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["derive"] }
desub-current = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
pretty_env_logger = { workspace = true }
