[workspace]
members = [
	"bin/tx-decoder",
	"bin/v14-test",
	"desub",
	"desub-current",
	"desub-legacy",
	"desub-json-resolver",
	"desub-common",
	"integration-tests",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "Apache-2.0"
repository = "https://github.com/paritytech/desub"
homepage = "https://github.com/paritytech/desub"
description = "Decode Substrate with Backwards-Compatible Metadata"
rust-version = "1.70.0"
edition = "2021"

[workspace.dependencies]
parity-scale-codec = "3.6.5"
scale-info = "2.10.0"
scale-value = "0.12.0"
scale-decode = "0.9"
frame-metadata = "16"
bitvec = "1"

sp-core = "24.0.0"
sp-runtime = "27.0.0"
sp-version = "25.0.0"
sp-keyring = "27.0.0"

pallet-balances = "24.0.0"
frame-system = "24.0.0"