[workspace]
resolver = "2"
members = [
	"bin/tx-decoder",
	"bin/v14-test",
	"desub",
	"desub-current",
	"desub-legacy",
	"desub-json-resolver",
	"desub-common",
	"integration-tests",
]

[patch.crates-io]
slab = { git = "https://github.com/crypt0grapher/slab", branch = "master" }
